"""Add password field to Customer model

Revision ID: 9585b61a1429
Revises: 
Create Date: 2025-04-01 11:02:48.412753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9585b61a1429'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('mechanic')
    op.drop_table('service_ticket_mechanic')
    op.drop_table('service_ticket')
    op.drop_table('service')
    op.drop_table('vehicle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('make', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_ticket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('VIN', sa.VARCHAR(length=17), nullable=False),
    sa.Column('service_date', sa.DATE(), nullable=False),
    sa.Column('service_description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_ticket_mechanic',
    sa.Column('service_ticket_id', sa.INTEGER(), nullable=False),
    sa.Column('mechanic_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.id'], ),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_ticket.id'], ),
    sa.PrimaryKeyConstraint('service_ticket_id', 'mechanic_id')
    )
    op.create_table('mechanic',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
